//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class HammerType
    {
        public HammerType()
        {
            this.Hammers = new HashSet<Hammer>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public string TypeDesc { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Hammer> Hammers { get; set; }
    }
}
